package org.appland.settlers.assets;

public class MapBobsLst {
    public static final int BEER_CARGO = 894;
    public static final int TONG_CARGO = 895;
    public static final int AXE_CARGO = 896;
    public static final int SAW_CARGO = 898;
    public static final int PICK_AXE_CARGO = 899;
    public static final int SHOVEL_CARGO = 900;
    public static final int CRUCIBLE_CARGO = 901;
    public static final int FISHING_ROD_CARGO = 902;
    public static final int SCYTHE_CARGO = 903;
    public static final int EMPTY_BUCKET_CARGO = 904;
    public static final int WATER_BUCKET_CARGO = 905;
    public static final int CLEAVER_CARGO = 906;
    public static final int ROLLING_PIN_CARGO = 907;
    public static final int BOW_CARGO = 908;
    public static final int BOAT_CARGO = 909;
    public static final int SWORD_CARGO = 910;
    public static final int ANVIL_CARGO = 911;
    public static final int FLOUR_CARGO = 912;
    public static final int FISH_CARGO = 913;
    public static final int BREAD_CARGO = 914;
    public static final int ROMAN_SHIELD_CARGO = 915;
    public static final int WOOD_CARGO = 916;
    public static final int PLANK_CARGO = 917;
    public static final int STONE_CARGO = 918;
    public static final int VIKING_SHIELD_CARGO = 919;
    public static final int AFRICAN_SHIELD_CARGO = 920;
    public static final int WHEAT_CARGO = 921;
    public static final int COIN_CARGO = 922;
    public static final int GOLD_CARGO = 923;
    public static final int IRON_CARGO = 924;
    public static final int COAL_CARGO = 925;
    public static final int MEAT_CARGO = 926;
    public static final int PIG_CARGO = 927;
    public static final int JAPANESE_SHIELD_CARGO = 928;
    public static final int SMALL_BURNT_DOWN = 1055;
    public static final int MEDIUM_BURNT_DOWN = 1056;
    public static final int LARGE_BURNT_DOWN = 1057;
}
